# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.right_rotate = QtWidgets.QToolButton(self.centralwidget)
        self.right_rotate.setGeometry(QtCore.QRect(480, 10, 26, 22))
        self.right_rotate.setObjectName("right_rotate")
        self.left_rotate = QtWidgets.QToolButton(self.centralwidget)
        self.left_rotate.setGeometry(QtCore.QRect(430, 10, 26, 22))
        self.left_rotate.setObjectName("left_rotate")
        self.zoom_out = QtWidgets.QToolButton(self.centralwidget)
        self.zoom_out.setGeometry(QtCore.QRect(320, 10, 26, 22))
        self.zoom_out.setObjectName("zoom_out")
        self.zoom_in = QtWidgets.QToolButton(self.centralwidget)
        self.zoom_in.setGeometry(QtCore.QRect(270, 10, 26, 22))
        self.zoom_in.setObjectName("zoom_in")
        self.image_box = QtWidgets.QLabel(self.centralwidget)
        self.image_box.setEnabled(True)
        self.image_box.setGeometry(QtCore.QRect(89, 55, 561, 291))
        self.image_box.setAutoFillBackground(False)
        self.image_box.setText("")
        self.image_box.setObjectName("image_box")
        self.load_image = QtWidgets.QPushButton(self.centralwidget)
        self.load_image.setGeometry(QtCore.QRect(100, 10, 101, 31))
        self.load_image.setObjectName("load_image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.right_rotate.setText(_translate("MainWindow", "D"))
        self.left_rotate.setText(_translate("MainWindow", "S"))
        self.zoom_out.setText(_translate("MainWindow", "-"))
        self.zoom_in.setText(_translate("MainWindow", "+"))
        self.load_image.setText(_translate("MainWindow", "Load image"))
